<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sun, 17 Oct 2021 19:54:34 +0000
 */
$conf['title'] = 'BalticStream';
$conf['lang'] = 'de';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
