# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sun, 17 Oct 2021 19:54:34 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$OF43hfivQh4OHYbOHoAqRO3wqVdaSOkyrmCbaJYSAJtMmh.YHV9L2:Baltic Taucher:matthias.harms@bi-concepts.org:admin,user
